/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import classes.DatosVegetales;
import classes.UsuarioAplicacion;
import classes.Validaciones;
import javax.swing.JOptionPane;

/**
 * Esta clase tiene el rol de ser la interfaz para un menu de usuario, dando varias opciones
 * de interaccion con el programa.
 * 
 * @author Cristóbal Cáceres
 * @author Pablo Araya
 * @author René Araya
 * @version 1.0
 */
public class MenuUsuario extends javax.swing.JFrame {

    private UsuarioAplicacion usuario;
    private DatosVegetales datos;
    private MenuUsuario ventanaUsuario;
    private Principal ventanaPrincipal;
    private Validaciones validaciones = new Validaciones();
    
    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
        initComponents();
    }

    public void setUsuario(UsuarioAplicacion usuario) {
        this.usuario = usuario;
    }

    public void setDatos(DatosVegetales datos) {
        this.datos = datos;
    }

    public void setVentanaUsuario(MenuUsuario ventanaUsuario) {
        this.ventanaUsuario = ventanaUsuario;
    }

    public void setVentanaPrincipal(Principal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarVegetal = new javax.swing.JButton();
        btnEliminarVegetal = new javax.swing.JButton();
        btnMostrarVegetales = new javax.swing.JButton();
        btnMostrarIMC = new javax.swing.JButton();
        btnMostrarCalCon = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarVegetal.setText("Agregar Vegetal");
        btnAgregarVegetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVegetalActionPerformed(evt);
            }
        });

        btnEliminarVegetal.setText("Eliminar Vegetal");
        btnEliminarVegetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVegetalActionPerformed(evt);
            }
        });

        btnMostrarVegetales.setText("Vegetales Consumidos");
        btnMostrarVegetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVegetalesActionPerformed(evt);
            }
        });

        btnMostrarIMC.setText("Mostrar IMC");
        btnMostrarIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarIMCActionPerformed(evt);
            }
        });

        btnMostrarCalCon.setText("Calorias Consumidas");
        btnMostrarCalCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCalConActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarCalCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarVegetales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarVegetal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarVegetal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addGap(67, 67, 67)
                .addComponent(btnAgregarVegetal)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarVegetal)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarVegetales)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarIMC)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarCalCon)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarVegetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVegetalActionPerformed
        
        ventanaUsuario.setVisible(false);
        datos.mostrarIdVegetales();
        int idVeg= validaciones.validarInt();
        int posVeg = datos.posicionDelIdVegetal(idVeg);
        
        if (usuario.agregarVegetal(datos.getListaVegetales().get(posVeg).getNombreVegetal(), datos.getListaVegetales().get(posVeg).getTipoVegetal(), posVeg+1))
            System.out.println("Vegetal agregado");
        else
            System.out.println("Vegetal no agregado");
        ventanaUsuario.setVisible(true);
    }//GEN-LAST:event_btnAgregarVegetalActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        ventanaUsuario.setVisible(false);
        ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEliminarVegetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVegetalActionPerformed

        ventanaUsuario.setVisible(false);
        usuario.mostrarVegetales();
        System.out.println("Ingresa un ID de un vegetal a eliminar");
        int idVeg = validaciones.validarInt();
        if (usuario.eliminarVegetal(idVeg))
            System.out.println("Vegetal eliminado");
        else
            System.out.println("Vegetal no eliminado");
        ventanaUsuario.setVisible(true);
    }//GEN-LAST:event_btnEliminarVegetalActionPerformed

    private void btnMostrarVegetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVegetalesActionPerformed
        usuario.mostrarVegetales();
    }//GEN-LAST:event_btnMostrarVegetalesActionPerformed

    private void btnMostrarIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarIMCActionPerformed
        usuario.calcularIMC();
        double imc = usuario.getImc();
        imc = Math.round(imc);
        String IMC = Double.toString(imc);
        JOptionPane.showMessageDialog(null, "Tu IMC es "+IMC);
    }//GEN-LAST:event_btnMostrarIMCActionPerformed

    private void btnMostrarCalConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCalConActionPerformed
        double calorias = usuario.getSumaCaloriasConsumidas(datos.getListaVegetales());
        String strCalorias = Double.toString(calorias);
        JOptionPane.showMessageDialog(null, "Tus calorías consumidas son "+strCalorias+"kcal");
    }//GEN-LAST:event_btnMostrarCalConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVegetal;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminarVegetal;
    private javax.swing.JButton btnMostrarCalCon;
    private javax.swing.JButton btnMostrarIMC;
    private javax.swing.JButton btnMostrarVegetales;
    // End of variables declaration//GEN-END:variables
}
